### ISSUE TITLE
Why was this extracted?

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli-test-loader#1]
This seems silly to extract this single file into a separate npm package. Managing changes between this file for the notifications as well as the fixtures I'd like to add and ember-cli itself is going to be a major pain

**Comment by rwjblue** [comment]
Not permaclosing this, but I think general thinking on this issue has changed over the last few months since it was opened.  I think pushing things out of ember-cli into addons is a good thing generally...
