### ISSUE TITLE
Does the "unable to require.unsee, please upgrade loader.js to >= v3.3.0" error refer to ember-cli/loader.js?

### ISSUE THREAD

**Issue by notmessenger** [ember-cli/ember-cli-test-loader#15]
In an Ember CLI 1.13.8 addon, with

```
"ember-cli-test-loader": "ember-cli-test-loader#0.2.1",
"loader.js": "ember-cli/loader.js#3.3.0"
```

when accessing `/tests` this error is displayed due to https://github.com/ember-cli/ember-cli-test-loader/blob/master/test-loader.js#L72

Should it be?  Seems I have the correct dependency but perhaps I'm not understanding the information/relationship correctly.

**Comment by rwjblue** [comment]
These dependencies versions seem correct (and should not warn), can you run:

`npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install`

To confirm all deps are up to date?

**Comment by notmessenger** [comment]
Interesting.  This error only occurs when I select the "Enable coverage" checkbox option at the `/tests` url.

**Comment by notmessenger** [comment]
Guess I should mention I also have ember-cli-blanket installed.  https://github.com/notmessenger/sl-ember-components/tree/ember-cli-blanket is what I'm currently running.

**Comment by rwjblue** [comment]
ember-cli-blanket overrides `require` with its custom function (that then calls the original one), and does not expose `require.unsee`.

https://github.com/sglanzer/ember-cli-blanket/blob/master/vendor/blanket-require.js

**Comment by rwjblue** [comment]
I'm going to close this for now (happy to reopen if this lib is still an issue), would you mind open an issue over there?

**Comment by toranb** [comment]
Just a quick note - I see this running node v4.1.1 after a fresh nom bom / npm install (after I upgraded from 1.13.8 to 1.13.11 on OSX)

Anyone else having this message show up in testem today? *might just be me*

**Comment by toranb** [comment]
Also noticed this on my co-workers machine running node v5.0.0 and npm v3.3.6

**Comment by rwjblue** [comment]
@toranb - This warning is not related to node/npm versions.  You need to have loader.js >= 3.3.0.

**Comment by toranb** [comment]
Makes sense -is this the loader you are referring to by chance? (from bower.json)

```
"loader.js": "ember-cli/loader.js#3.2.1",
```

**Comment by rwjblue** [comment]
yes, you need 3.3.0 (as the message indicates)

**Comment by toranb** [comment]
Sorry for what in retrospect looks like "programming 101" here @rwjblue - I suppose the funny part is that I "thought" my ember-cli upgrade would have fixed this (but user error (on my end) is the number one cause of programming 101 syndrome).

thanks for holding my hand on this one again :)

**Comment by rwjblue** [comment]
I believe that 1.13.13 has the correct versions included.
