### ISSUE TITLE
v1.0.0 vs v0.2.2

### ISSUE THREAD

**Issue by ankushdharkar** [ember-cli/ember-cli-test-loader#19]
I currently have `"ember-cli-test-loader": "0.2.2"` in my `bower.json`. Whenever I run an update for bower packages, it is always updated to `1.0.0` which throws error messages on running `ember server`.

Should we remove it from `bower.json` and install it as an ember addon, or should we refrain from using `1.0.0` until further notice? 

I am a little confused because in the [releases](https://github.com/ember-cli/ember-cli-test-loader/releases/), it says that `0.2.2` is the current release.

Would appreciate your help. Thanks

**Comment by rwjblue** [comment]
1.0.0 will move to `package.json` from `bower.json`, but that is not enabled yet.  The default ember-cli blueprint specifies 0.2.2 which should definitely not allow 1.0.0.

**Comment by ankushdharkar** [comment]
Got it. Thanks you for replying quickly.
