### ISSUE TITLE
Should the default behaviour skip importing error tests?

### ISSUE THREAD

**Issue by ppcano** [ember-cli/ember-cli-test-loader#25]
The current [require method](https://github.com/ember-cli/ember-cli-test-loader/blob/master/addon-test-support/index.js#L74) skips tests that fails when importing. An error importing a test will not fail the test suite. I think, the default behaviour should not be to silence this kind of errors.

**Comment by rwjblue** [comment]
The default behavior in this library is just a stub that should be replaced with whatever test framework specific code that is needed.

Out of the box, Ember CLI comes with `ember-cli-qunit` which does generate a failed test ([see here](https://github.com/ember-cli/ember-cli-qunit/blob/master/vendor/ember-cli-qunit/test-loader.js#L28-L31)).

**Comment by ppcano** [comment]
Then, my problem is that my test setup does not load `ember-cli-qunit`.

@rwjblue Thanks for the explanation.

**Comment by ppcano** [comment]
The root of the problem was described at ember-cli/ember-cli-qunit#100

When a test filter is applied, the test load errors are not reported.
