### ISSUE TITLE
`npm publish` for 1.1.1

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-test-loader#29]
I just fixed an issue (deprecation showing on latest ember-cli), and updated the version number / tagged but then realized I can't `npm publish`.

@stefanpenner - Can you add me to `npm` and/or publish?

**Comment by stefanpenner** [comment]
> @stefanpenner - Can you add me to npm and/or publish?

Done

**Comment by stefanpenner** [comment]
@rwjblue wanna release or should i?

**Comment by rwjblue** [comment]
Done, thank you for adding me
