### ISSUE TITLE
Where is the correct place to override TestLoader now?

### ISSUE THREAD

**Issue by Bushjumper** [ember-cli/ember-cli-test-loader#30]
Hey there :)

I'm attempting to upgrade to Ember 2.7.0 and beyond. One of the required changes is that the ember-cli-test-loader bower dependency has been replaced by this NPM-based one.

The README for this repo mentions overriding TestLoader as follows "Within your test suite" :

```js
var TestLoader = require('ember-cli/test-loader')['default'];
```

That no longer works as expected, which makes sense. I was previously doing the override in tests/index.html - where should it be done now and what is the correct way to require/include the NPM based dependency?

I'd be happy to update the README once I get it working, with your guidance.

Thanks

**Comment by Turbo87** [comment]
@Bushjumper see e.g. https://github.com/ember-cli/ember-cli-mocha/blob/b21ddf074a5a067a647afd2c3e95fba92453575d/vendor/ember-cli-mocha/test-loader.js#L4-L13

may I ask why you want to override the test loader though? what are your special needs that require you to do that?

**Comment by Bushjumper** [comment]
@Turbo87 thanks for the quick response! I'll see if that works. I just need to exclude certain tests from running using loadModules, shouldLoadModule or similar.

**Comment by rwjblue** [comment]
Closing, I believe the question was answered...
