### ISSUE TITLE
add similar jscs functionality if detected

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-test-loader#5]
Do you think it would be possible to add a "Disable JSCS" check box next to the "Disable JSHint" check box if jscs/broccoli-jscs is detected? I will do the research/pull-requests if you think it would be a suitable addition.

**Comment by rwjblue** [comment]
@kellyselden - Still interested here?

**Comment by kellyselden** [comment]
@rwjblue I was thinking about this recently. Yes still interested.

**Comment by rwjblue** [comment]
I believe that this is taken care of now. All "linting" should result in the extension `-lint-test.js` and things should "just work"...
