### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by fkm** [ember-cli/ember-cli-test-loader#56]
This is yet another package that keeps installing ember-cli-babel 6.x while the corresponding dependency update would already be in the repository.

**Comment by Turbo87** [comment]
what's wrong with installing ember-cli-babel 6.x?

**Comment by fkm** [comment]
I have a host of dependencies double. For example babel-preset-env which is installed by ember-cli-babel 6 while current packages install @babel/preset-env.

**Comment by Turbo87** [comment]
does that create any issues other than using more disk space?

**Comment by fkm** [comment]
I'm currently debugging:

> Build Error (Analyzer)
> Duplicate plugin/preset detected.

The package in question is babel-plugin-transform-async-to-generator.

It's not sure that this is a problem with the duplicate installations. But I have a question too:
What is the reason *not* to make a new release?

**Comment by fkm** [comment]
Especially, since the last release is **over 2 years old**.

**Comment by Turbo87** [comment]
Updating ember-cli-babel is a breaking change, which means that this would have to be a new major version release, which leads all of our depending projects to potentially also have to do a new major version release.

**Comment by fkm** [comment]
So what?

**Comment by dmzza** [comment]
@Turbo87 Is there a particular milestone that you're waiting for? Or would it be too much work for too small a payoff?

If there is anything I can do to help, I'm offering. 

The problem this causes isn't easy to explain, but this is one bad link in a chain of outdated dependencies that I believe causes this problem: https://github.com/postcss/autoprefixer/issues/1184

I realize how crazy that sounds, but on the other hand, it would be strange if there were literally no consequences for withholding updates to this package, which many projects depend on, for two years.

**Comment by Turbo87** [comment]
v3.0.0 is released

**Comment by dmzza** [comment]
Thank you @Turbo87 

I was going to follow up next to make sure `ember-qunit`'s dependency on `ember-cli-test-loader` can be bumped to 3.0.0, but it looks like you're already there with a PR to drop Node 6 and 8. And I assume Dependabot will open a PR to bump the version.

**Comment by Turbo87** [comment]
yep

**Comment by Turbo87** [comment]
feel free to open more PRs that remove Node 6/8 support, but make sure to add an indication that these should be considered breaking changes and require major version bumps
